name: waktusolat_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/mptwaktusolat/waktusolat_api_client

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
